# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6cc76ab3348d651fa92336344670ce12b4f0320bb04cf04e30b776bd8d6f6847b5dead8c84a04b679b9beffeabcf43d8b6ebbcb53ab1c1a8a64799c027e3aff5

test:
  secret_key_base: 99484080e35bf55938b4fbfb1eb676e78a8cf81eb7063cfd5eaac0db1251081dbadf4b74051ada8c85099d2e07c8d70b2f5d2133cc8dd9deb6a21170c64cc97e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
